name: JawaChat
main: jawamaster.jawachat.JawaChat
description: Controls chat functions and supplies various administrative commands.
version: 2.0
api-version: 1.15
depends: JawaPermissions, JawaCore
commands:
  setnick:
    description: Used to set the player's nick name
    usage: /setnick <playername> [player nick name]
    permission: jawachat.setnick
  settag:
    description: Used to give a player a tag.
    usage: /settag <playername> [tag]
    permission: jawachat.settag
  setstar:
    description: Used to give a player a red or green star preceeding their name.
    usage: /setstar <playername> [r or g]
    permission: jawachat.setstar
  pm:
    description: Send a private message to a player
    usage: /pm <player> <Your message>
    permission: jawachat.pm
  mute:
    description: "Allows an admin to mute a player"
    usage: "/mute <player>"
    permission: jawachat.mute
  discordlink:
    description: "Generates a linking code to be used with the FoxelBot discord bot"
    usage: "/discordlink"
    permission: jawachat.discordlink
  breakcommand:
    permission: breakcommand
    
permissions:
  jawachat.discordlink:
    description: "Allows linking of an account to discord"
    default: true
  jawachat.mute:
    description: "Allows access to the /mute command"
    default: op
  jawachat.pm:
    description: "Allows a player to private message others"
    default: true
  jawachat.setstar:
    description: "Allows an admin to set a star on the player specified"
    default: op
  jawachat.settag:
    description: "Allows an admin to set a tag on the player specified"
    default: op
  jawachat.setnick:
    description: "Allows an admin to set the nickname of the player specified"
    default: op
  breakcommand:
    default: true